name = "MindReader"
uuid = "29767591-7395-4f5d-bb0f-9767abbb8d26"
authors = ["DanielRivasMD <danielrivasmd@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
